package com.java.oops;
public class Main {
    public static void main(String[] args) {
        Product product1 = new Product();
        Product product2 = new Product("shoe",5223,"boats","campus","useful for Sports",999,(byte) 10,900,4.5F,(short) 105,false,(byte) 10);
        System.out.println("-----------Product1 Details-----------");
        product1.displayProductDetails();
        System.out.println("-----------Product2 Details-----------");
        product2.displayProductDetails();
        Customer customer1 = new Customer();
        System.out.println("-----------Customer1 Details------------");
        System.out.println("Customer ID:" + customer1.id);
        System.out.println("Customer Name:" + customer1.name);
        System.out.println("Phone Number:" + customer1.phoneNo);
        System.out.println("EmailID:" + customer1.emailId);
        System.out.println("Gender:" + customer1.gender);
        System.out.println("Password:" + customer1.password);
        System.out.println("Pincode:" + customer1.pincode);
        System.out.println("Address:" + customer1.address);
        Customer customer2 = new Customer("sai",12342,"sai@14235",939234567L,'M',"7645363",522647,"vinukonda");
        System.out.println("----------------Customer2 Details--------------");
        System.out.println("Customer ID:" + customer2.id);
        System.out.println("Customer Name:" + customer2.name);
        System.out.println("Phone Number:" + customer2.phoneNo);
        System.out.println("EmailID:" + customer2.emailId);
        System.out.println("Gender:" + customer2.gender);
        System.out.println("Password:" + customer2.password);
        System.out.println("Pincode:" + customer2.pincode);
        System.out.println("Address:" + customer2.address);
        Order order = new Order();
        System.out.println("--------------- Order1 Details ------------");
        System.out.println("Order ID:" + order.orderId);
        System.out.println("User ID:" + order.userId);
        System.out.println("Product:" + order.productName);
        System.out.println("Total Amount:" + order.totalAmount);
        System.out.println("Status:" + order.status);
        System.out.println("Order Date:" + order.orderDate);
        System.out.println("Delivery Date:" + order.deliveryDate);
        System.out.println("Shipping Address:" + order.shippingAddress);
        System.out.println("Payment Status:" + order.paymentStatus);
        Order order1 = new Order(52261,522647,"Shirt",1999,"order is picking","22-12-1997","17-01-1998","Guntur,India",false);
        System.out.println("--------------- Order2 Details ------------");
        System.out.println("Order ID:" + order1.orderId);
        System.out.println("User ID:" + order1.userId);
        System.out.println("Product:" + order1.productName);
        System.out.println("Total Amount:" + order1.totalAmount);
        System.out.println("Status:" + order1.status);
        System.out.println("Order Date:" + order1.orderDate);
        System.out.println("Delivery Date:" + order1.deliveryDate);
        System.out.println("Shipping Address:" + order1.shippingAddress);
        System.out.println("Payment Status:" + order1.paymentStatus);
    }
}