package com.java.oops;
public class Main {
    public static void main(String[] args) {
        Product product1 = new Product();
        Product product2 = new Product();
        product1.id = 522141;
        product1.category = "Shirt";
        product1.name = "U.S. Polo Assn. Denim Co.";
        product1.company = "Us Polo";
        product1.description = "Pure Cotton Casual Shirt";
        product1.rating = 4.3F;
        product1.ratingCount = 304;
        product1.maxRetailPrice = 1999;
        product1.discountPercentage = 23;
        product1.finalSellingPrice = 1539;
        product1.size = 38;
        product2.id = 31472271;
        product2.category = "Shirt";
        product2.name = "Campus Sutra Shirt";
        product2.company = "Campus Sutra";
        product2.description = "Men Comfort Opaque Checked Casual Shirt";
        product2.rating = 3.8F;
        product2.ratingCount = 2000;
        product2.maxRetailPrice = 1999;
        product2.discountPercentage = 40;
        product2.finalSellingPrice = 1199;
        product2.size = 40;
        System.out.println("-----------Product1 Details-----------");
        System.out.println("ID:" + product1.id);
        System.out.println("Category:" + product1.category);
        System.out.println("Name:" + product1.name);
        System.out.println("Company:" + product1.company);
        System.out.println("Description:" + product1.description);
        System.out.println("Rating" + product1.rating);
        System.out.println("Rating Count:" + product1.ratingCount);
        System.out.println("MRP:" + product1.maxRetailPrice);
        System.out.println("Discount Percentage:" + product1.discountPercentage);
        System.out.println("Final Selling:" + product1.finalSellingPrice);
        System.out.println("Size:" + product1.size);
        System.out.println("-----------Product2 Details-----------");
        System.out.println("ID:" + product2.id);
        System.out.println("Category:" + product2.category);
        System.out.println("Name:" + product2.name);
        System.out.println("Company:" + product2.company);
        System.out.println("Description:" + product2.description);
        System.out.println("Rating" + product2.rating);
        System.out.println("Rating Count:" + product2.ratingCount);
        System.out.println("MRP:" + product2.maxRetailPrice);
        System.out.println("Discount Percentage:" + product2.discountPercentage);
        System.out.println("Final Selling:" + product2.finalSellingPrice);
        System.out.println("Size:" + product2.size);
        Customer customer1 = new Customer();
        customer1.id = 52214189;
        customer1.name = "Adithya";
        customer1.phoneNo = 9392723505L;
        customer1.emailId = "vajrlaadithya@gmail.com";
        customer1.gender = 'M';
        customer1.password = "123445";
        customer1.pincode = 522647;
        customer1.address = "Chatragaddapadu,vinukonda,palnadu,Andhra pradesh";
        System.out.println("-----------Customer1 Details------------");
        System.out.println("Customer ID:" + customer1.id);
        System.out.println("Customer Name:" + customer1.name);
        System.out.println("Phone Number:" + customer1.phoneNo);
        System.out.println("EmailID:" + customer1.emailId);
        System.out.println("Gender:" + customer1.gender);
        System.out.println("Password:" + customer1.password);
        System.out.println("Pincode:" + customer1.pincode);
        System.out.println("Address:" + customer1.address);
        Customer customer2 = new Customer();
        customer2.id = 52214188;
        customer2.name = "sai";
        customer2.phoneNo = 9392623505L;
        customer2.emailId = "nusumaadithya@gmail.com";
        customer2.gender = 'M';
        customer2.password = "1234@153";
        customer2.pincode = 522601;
        customer2.address = "Chatragaddapadu,vinukonda,palnadu,Andhra pradesh";
        System.out.println("----------------Customer2 Details--------------");
        System.out.println("Customer ID:" + customer2.id);
        System.out.println("Customer Name:" + customer2.name);
        System.out.println("Phone Number:" + customer2.phoneNo);
        System.out.println("EmailID:" + customer2.emailId);
        System.out.println("Gender:" + customer2.gender);
        System.out.println("Password:" + customer2.password);
        System.out.println("Pincode:" + customer2.pincode);
        System.out.println("Address:" + customer2.address);
    }
}