package com.java.oops;
public class Main {
    public static void main(String[] args) {
        Product product1 = new Product();
        Product product2 = new Product("shoe",5223,"boats","campus","useful for Sports",999,(byte) 10,900,4.5F,(short) 105,false,(byte) 10);
        System.out.println("-----------Product1 Details-----------");
        System.out.println("ID:" + product1.id);
        System.out.println("Category:" + product1.category);
        System.out.println("Name:" + product1.name);
        System.out.println("Company:" + product1.company);
        System.out.println("Description:" + product1.description);
        System.out.println("Rating" + product1.rating);
        System.out.println("Rating Count:" + product1.ratingCount);
        System.out.println("MRP:" + product1.maxRetailPrice);
        System.out.println("Discount Percentage:" + product1.discountPercentage);
        System.out.println("Final Selling:" + product1.finalSellingPrice);
        System.out.println("Size:" + product1.size);
        System.out.println("-----------Product2 Details-----------");
        System.out.println("ID:" + product2.id);
        System.out.println("Category:" + product2.category);
        System.out.println("Name:" + product2.name);
        System.out.println("Company:" + product2.company);
        System.out.println("Description:" + product2.description);
        System.out.println("Rating" + product2.rating);
        System.out.println("Rating Count:" + product2.ratingCount);
        System.out.println("MRP:" + product2.maxRetailPrice);
        System.out.println("Discount Percentage:" + product2.discountPercentage);
        System.out.println("Final Selling:" + product2.finalSellingPrice);
        System.out.println("Size:" + product2.size);
        Customer customer1 = new Customer();
        System.out.println("-----------Customer1 Details------------");
        System.out.println("Customer ID:" + customer1.id);
        System.out.println("Customer Name:" + customer1.name);
        System.out.println("Phone Number:" + customer1.phoneNo);
        System.out.println("EmailID:" + customer1.emailId);
        System.out.println("Gender:" + customer1.gender);
        System.out.println("Password:" + customer1.password);
        System.out.println("Pincode:" + customer1.pincode);
        System.out.println("Address:" + customer1.address);
        Customer customer2 = new Customer("sai",12342,"sai@14235",939234567L,'M',"7645363",522647,"vinukonda");
        System.out.println("----------------Customer2 Details--------------");
        System.out.println("Customer ID:" + customer2.id);
        System.out.println("Customer Name:" + customer2.name);
        System.out.println("Phone Number:" + customer2.phoneNo);
        System.out.println("EmailID:" + customer2.emailId);
        System.out.println("Gender:" + customer2.gender);
        System.out.println("Password:" + customer2.password);
        System.out.println("Pincode:" + customer2.pincode);
        System.out.println("Address:" + customer2.address);
    }
}